# Python Assignment 3

⏱⏱⏱**Due: 11/02/2023 11:59 PM** ⏱⏱⏱

Please submit your notebook files and upload them to your Git repository. Don't forget to include a link to your Git repository when submitting this file on Brightspace. **Please include all outputs in your notebook, including plots, printouts, etc..**

Collaboration is permitted and encouraged; however, it's essential to independently produce and submit your own work. If you collaborate with others, please ensure that you provide their names in the designated section.

Collaborators:_____

##**For Questions 2a and 2b, you can choose one of them to complete, if you completed both, only Questions 2a will be graded.**

**This assignment is out of 150 points; surplus points can be applied to other assignments (including Matlab and C/C++). However, it cannot be applied to your final project grade, and your assignment grade will not excced 75% of your total grade.**

## 1. Good presentation of your code and outputs; submitting your files to Github (10 pts)

Ensure thorough and clear comments within your code to explain its functionality.

Enhance your plots by adding titles, legends, and axis labels where appropriate to provide clarity.

If necessary, employ LaTex notation to present mathematical explanations within the notebook.

Divide your code into multiple blocks or cells in Jupyter Notebook and provide descriptive explanations for each block to improve readability.

As part of your submission, **include the notebook files and upload them to your Git repository. Additionally, remember to provide a link to your Git repository when submitting the files on Brightspace.** Do not submit a compressed file (.rar, .zip, etc..), submit files separately.

If you are tasked with implementing a numerical algorithm, it is expected that you would not rely on pre-existing methods. For example, if you were asked to solve $Ax=b$, you should write your own program to solve, not just by calling numpy.linalg.solve.



## 2a. Numerical Integration (30 pts)

For a domain discretized into $N$ equally spaced panels:
$$
\Delta x=\frac{b-a}{N}.
$$
The approximation to the integral is
$$\begin{aligned}
\int_a^b f(x) d x & \approx \frac{\Delta x}{2} \sum_{k=1}^N\left(f\left(x_{k-1}\right)+f\left(x_k\right)\right) \\
& =\frac{\Delta x}{2}\left(f\left(x_0\right)+2 f\left(x_1\right)+2 f\left(x_2\right)+2 f\left(x_3\right)+\cdots+2 f\left(x_{N-1}\right)+f\left(x_N\right)\right) \\
& =\Delta x\left(\sum_{k=1}^{N-1} f\left(x_k\right)+\frac{f\left(x_N\right)+f\left(x_0\right)}{2}\right) .
\end{aligned}$$
This is the trapezoid rule scheme.


Given the function $f(x) = 3x^2 + 2x +2$, your tasks are:

1. Carry out the integration symbolically using the SymPy library. Output the result (i.e. print out the result).
2. Implement the trapezoid rule to estimate the integral $\int_{-4}^6 f(x) dx$ using the following values of $N = 10, 20, 40, 80, 160, 320, 640, 1280$. Output the results (i.e. print out the results).
3. Plot the absolute error (absolute difference between the numerical approximation and the SymPy result) against N.





In [180]:
from sympy import *
init_printing()
x = Symbol('x')
t = (3*x**2)+2*x+2
integrate(t, (x, -4, 6))


In [7]:
def f(x):
    return (3*x**2)+2*x+2

def sum(n, a, b):
    delt_x = (b-a)/n
    running_sum = 0
    for k in range(1,n):
        x_k = a + (delt_x * k)
        running_sum += f(x_k)
    mid = (f(b) + f(a))/2
    return delt_x * (running_sum + mid)

N = [10, 20, 40, 80, 160, 320, 64, 1280]
N_results = []
for i in N:
    N_results.append(sum(i,-4,6))
    

print(N_results)








[325.0, 321.25, 320.3125, 320.078125, 320.01953125, 320.0048828125, 320.1220703125, 320.00030517578125]


## 2b. Numerical Differentiation (30 pts)

Your tasks:
1. Find the closed form expression of $f_{xy}(x,y)$, i.e. $\frac{d^2}{dxdy}f(x,y)$, for $f(x,y) = \left(sin^2\left(x\right)e^xcos(y)\right)$ using `sympy`. Output the result.
2. Find $f_{xy}(2,3)$ with `sympy` and take 15 significant digits, use it as the "groud truth solution". Output the result.
3. Approximate $f_{xy}(2,3)$ using central difference approximation for the following values of $h = 0.1, 0.01, 0.001, 0.0001$. Output the results.
4. Plot the absolute error (absolute difference between the numerical approximation and the SymPy result) against the step size $h$. `plt.gca().invert_xaxis() ` might help.

Recall from the lecture:
$$f_{x y}(x, y) \approx \frac{f(x+h, y+k)-f(x+h, y-k)-f(x-h, y+k)+f(x-h, y-k)}{4 h k}.$$
For simplicity, we set $k = h$.

## 3. Pandas I (15 pts)

1. Create a 3x4 (3 rows by 4 columns) pandas DataFrame with the columns named after the following Long Island towns: Hempstead, Babylon, Islip, and Brookhaven. The rows represent 'Population in 2099', 'Population in 2300', 'Population in 2400'. Fill each of the 12 cells in the DataFrame with a random integer from 1000 to 10000, inclusive. `np.random.randint()` might be helpful.
For Example:

```
                    Hempstead  Babylon  Islip  Brookhaven
Population in 2099       2931     8043   8414        8661
Population in 2300       5444     9227   7393        8007
Population in 2400       1660     7977   4730        2940
```



2. Output the following:
  - The entire DataFrame.
  - The value in the cell of row #1 (indexing starts with 0) under the Hempstead column.

3. Add a new column named Riverhead. Populate this column with the sum of the respective row values from the Islip and Brookhaven columns. Output the entire DataFrame again.

In [84]:
import pandas as pd

Hempstead = [2931, 5444, 1660]
Babylon = [8043, 9227, 7977]
Islip = [8414, 7393, 4730]
Brookhaven = [8661, 8007, 2940]
Population = ["Population in 2099", "Population in 2300", "Population in 2400"]

df = pd.DataFrame({"": Population, "Hempstead":Hempstead, "Babylon":Babylon, "Islip":Islip, "Brookhaven":Brookhaven})
df

Hempstead  Babylon  Islip  Brookhaven
0  Population in 2099       2931     8043   8414        8661
1  Population in 2300       5444     9227   7393        8007
2  Population in 2400       1660     7977   4730        2940

In [91]:
df["Hempstead"][0]

2931

In [92]:
df["Riverhead"] = df["Islip"]+df["Brookhaven"]
df

Hempstead  Babylon  Islip  Brookhaven  Riverhead
0  Population in 2099       2931     8043   8414        8661      17075
1  Population in 2300       5444     9227   7393        8007      15400
2  Population in 2400       1660     7977   4730        2940       7670

## 4. Pandas II (15 pts)

0. Download the cvs file that comes with this assignment, and read it into a dataframe. You can also download this [csv file](https://media.githubusercontent.com/media/datablist/sample-csv-files/main/files/customers/customers-100.csv) with this link.
1. Arrange the data in alphabetical order based on the last name. Display the first few rows.
2. Count the number of customers whose subscription date is in 2021 (2021-01-01 to 2021-12-31). Report this number (e.g. print).

In [98]:
df2 = pd.read_csv("C:/Users/nicm9/OneDrive/Documents/AMS595/PythonHw3/customers-100.csv")
df2.sort_values("Last Name").head()

Index      Customer Id First Name Last Name                Company  \
67     68  a014Ec1b9FccC1E        Tom  Alvarado    Donaldson-Dougherty   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson  Ware, Burns and Oneal   
92     93  aAb6AFc7AfD0fF3     Collin     Ayers          Lamb-Peterson   
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter        Rasmussen Group   
15     16  8cad0b4CBceaeec    Miranda   Beasley     Singleton and Sons   

                City    Country             Phone 1                Phone 2  \
67  South Sophiaberg   Kiribati  (585)606-2980x2258      730-797-3594x5614   
96      New Bradview  Sri Lanka     +1-846-706-2218           605.413.3198   
92      South Lonnie   Anguilla    404-645-5351x012  001-257-582-8850x8516   
0       East Leonard      Chile        229.077.5154       397.884.0519x718   
15      Desireeshire       Oman    540.085.3135x185  +1-600-462-6432x21881   

                            Email Subscription Date  \
67  nicholsonnina@montgomery.info        2020-08-18   
96              vkemp@ferrell.com        2021-07-10   
92       dudleyemily@gonzales.biz        2021-06-29   
0        zunigavanessa@smith.info        2020-08-24   
15        vduncan@parks-hardy.com        2022-04-12   

                       Website  
67     http://odom-massey.com/  
96  https://novak-allison.com/  
92        http://www.ruiz.com/  
0   http://www.stephenson.com/  
15          http://acosta.org/

In [107]:
subscription_date = df2[(df2['Subscription Date'] > '2021-01-01') & (df2['Subscription Date']< '2021-12-31')]
len(subscription_date)

## 5. LU decomposition (50 + 30 pts)


Part A (50 points)
1. Write a function `LUdecomposition()` that takes as input a matrix $A\in \mathbb{R}^{n \times n}$. Perform Gaussian Elimination to have this function return two matrices $L$ and $U$ such that $A=LU$.
2. Your function should raise any relevant errors, for example, raise an error if a pure LU decomposition does not exist for $A$ (meaning that you have to perform pivoting, i.e., permutation of rows).
3. Create several random matrices for the purpose of testing your function. Obtain the $L$ and $U$ matrices, and for each random matrix obtain its L and U matrices and perform a matrix multiplication (`np.matmul()`) to determine whether the outcome closely resembles the original matrix $A$, allowing for slight differences attributable to precision errors.


Note: LU decomposition with Gaussian elimination should be covered in your undergraduate linear algebra class. It is also covered in AMS 510. If you do not know how, this 10 minute [video](https://www.youtube.com/watch?v=UlWcofkUDDU&ab_channel=Mathispower4u) explains it very well.

Part B (30 bonus points)
4. Not all square matrices have a pure LU decomposition. However, PLU decomposition always exists. Write another function `pivoting()` that takes as input a matrix $A$ and return the permutation/pivoting matrix $P$ such that $PA$ always has a pure LU decomposition.
5. Find an example $A$ for which `LUdecomposition()` raises an error. Then, use `pivoting()` to find $P$, and find the pure LU decomposition of $PA$. Verify that indeed $PA = LU$ with matrix multiplication (`np.matmul()`).


Hint: Please do not print out a giant matrix and visually examine the outcomes. Think of a way to verify your results and output a boolean value.


Fact: LU and PLU decompositions are not unique.

In [ ]:
#should be another error that is not listed here as well
#np.allclose() check if the 2 matrices are equal to each other 

In [8]:
import numpy as np
a = np.array([[10, -20, 10], [2, 1, -3], [4, -7, 1]])


def LUdecomposition(matrix_a):

    num_rows, num_cols = np.shape(matrix_a)


    matrix_u = matrix_a.copy()

    for col in range(num_rows-1):
        for row in range(col + 1,num_rows):
            cur_cell = matrix_u[row,col]
            cur_pivot = matrix_u[col,col]
            fraction = cur_cell/cur_pivot
            modified_top_row = fraction * matrix_u[col,:]
            matrix_u[row,:] = matrix_u[row,:] - modified_top_row

    matrix_l = np.zeros(np.shape(matrix_a))

    for col in range(num_cols):
        for row in range(col, num_cols):

            if col == row:
                matrix_l[row,col] = 1
            else:

                minus = 0
                for j in range(col):
                    minus+= matrix_l[row,j] * matrix_u[j, col]
                
                matrix_l[row,col] = (matrix_a[row,col] - minus)/matrix_u[col,col]

    return matrix_l, matrix_u



L, U = LUdecomposition(a)
print(f"A: {a}")
print(f"L: {L}")
print(f"U: {U}")

print(f"A = LU?\n {a} = {np.matmul(L,U)}")



A: [[ 10 -20  10]
 [  2   1  -3]
 [  4  -7   1]]
L: [[1.  0.  0. ]
 [0.2 1.  0. ]
 [0.4 0.2 1. ]]
U: [[ 10 -20  10]
 [  0   5  -5]
 [  0   0  -2]]
A = LU?
 [[ 10 -20  10]
 [  2   1  -3]
 [  4  -7   1]] = [[ 10. -20.  10.]
 [  2.   1.  -3.]
 [  4.  -7.   1.]]


## 6. Markov Chain (30 pts)

**BACKGROUND:** Consider a Markov chain transition matrix $P$ on a set of $n$ states, where $P_{i j}$ corresponds to the probability $\left(0 \leq P_{i j} \leq 1\right)$ to go from state $i$ to the state $j$, and each row is normalized so that
$$
\sum_{j=1}^n P_{i j}=1 .
$$

Let $p$ be a size- $n$ vector composed of the probability distribution over the $n$ states, where
$$
\sum_{j=1}^n p_j=1 .
$$

The transition rule corresponding to the transition matrix $P$ is $\hat{p}=P^T p$, where $\hat{p}$ corresponds to a new probability distribution and
$$
\sum_{j=1}^n \hat{p}_j=1 .
$$
TASK: Write a program that works with 5 states `only use the numpy library`. In particular,
0. Fix the random seed to be the last digit of your id: `numpy.random.seed()`.

1. Construct a random $5 \times 5$ matrix $P$, and normalize each row so that
$$
\sum_{j=1}^5 P_{i j}=1 .
$$

2. Construct a random size-5 vector $p$ and normalize it so that
$$
\sum_{j=1}^5 p_j=1 .
$$
Apply the transition rule 50 times to obtain $p_{50}$.
3. Compute the eigenvector $v$ of $P^T$ corresponding to the eigenvalue 1 (and numerically, the eigenvalue closest to $1)$, and then scale the eigenvector so that
$$
\sum_{j=1}^5 v_j=1 .
$$
This scaled eigenvector is known as the stationary distribution.

4. Compute the component wise difference between $p_{50}$ and the stationary distribution. Do they match with each other within $1 \mathrm{e}-5$ ?

HINTS: You may find the following functions useful in your implementation:
- np.random.rand
- np.dot
- np.linalg.eig

# 1

In [9]:
import numpy as np

def gen_mat_P():
    np.random.seed(8)

    P = np.random.rand(5,5)
    
    for i in range(len(P)):
        row = P[i]
        P[i] = row/row.sum()
    return P

def check(array):
    for row in array:
        print(row.sum())
    
P = gen_mat_P()
check(P)

1.0
1.0
1.0
1.0
1.0000000000000002


# 2

In [10]:
def gen_row_p():
    np.random.seed(8)
    p = np.random.rand(5)
    p = p/p.sum()
    
    return p
     
p = gen_row_p()

print(f"row vector p: {p}")
print(f"Sum of row vector probabilities (should be close to 1 since it is a prob distro): {p.sum()}")

row vector p: [0.25136477 0.2787369  0.25014602 0.15277528 0.06697703]
Sum of row vector probabilities (should be close to 1 since it is a prob distro): 1.0


In [11]:
# Apply transition 50 times

p50 = p

for _ in range(50):
    p50 = np.dot(P.T, p50)
    
print(f"p50: {p50}")

print(f"p50 should still be a probability distribution so it's sum should also be close to 1: {p50.sum()}")

p50: [0.12304366 0.26075232 0.25213473 0.21172295 0.15234634]
p50 should still be a probability distribution so it's sum should also be close to 1: 1.0000000000000009


# 3

In [13]:
eig = np.linalg.eig(P.T)

values, vectors = eig

print(f"Eigenvalues:\n {values}")
print(f"Real parts of Eigenvalues:\n {values.real}")

print("\n\n\n")
# index_of_1 = list(values).index(1.)

# print(index_of_1)


print(vectors.real)


real_values = values.real
# Find the index of eigenvalue 1, may not be exact so search for closest one
minimum_diff = 1
index_of_1 = -1
for i in range(len(real_values)):
    current = real_values[i]
    if abs(current-1) < minimum_diff:
        minimum_diff = abs(current-1)
        index_of_1 = i
        
print(index_of_1)

# Can discard imaginary part, will be 0 anyway
# Need to get the column due to .eig returns the vectors
nonnormalized_eigenvector = vectors[:, index_of_1].real
print(f"Eigenvector: {nonnormalized_eigenvector}")

stationary_distribution = nonnormalized_eigenvector/nonnormalized_eigenvector.sum()

print(f"Stationary distribution: {stationary_distribution}")



print(np.dot(P.T, stationary_distribution))

Eigenvalues:
 [ 1.         -0.24030228  0.17916363  0.00274744 -0.02446717]
Real parts of Eigenvalues:
 [ 1.         -0.24030228  0.17916363  0.00274744 -0.02446717]




[[ 0.26552372 -0.17585855  0.85372881  0.59694582 -0.50401666]
 [ 0.56269397 -0.7544231  -0.30409957  0.41629511 -0.46941504]
 [ 0.54409753  0.10330101  0.0445187  -0.62905716  0.6885893 ]
 [ 0.45689037  0.25970481 -0.28751419 -0.17156654  0.06861777]
 [ 0.32875784  0.56727583 -0.30663375 -0.21261723  0.21622464]]
0
Eigenvector: [0.26552372 0.56269397 0.54409753 0.45689037 0.32875784]
Stationary distribution: [0.12304366 0.26075232 0.25213473 0.21172295 0.15234634]
[0.12304366 0.26075232 0.25213473 0.21172295 0.15234634]


# 4

In [14]:
# What is component wise difference?

print(stationary_distribution - p50)

[-1.80411242e-16 -2.77555756e-16 -5.55111512e-17 -1.94289029e-16
 -2.77555756e-17]
